#pragma once

#include <cstdint>

enum EsfStatus : uint8_t {
    ESF_SUCCESS = 0,
    ESF_TIMEOUT,
    ESF_MULTIPLE_ERROR,
    ESF_QUEUE_FULL,
    ESF_QUEUE_EMPTY,
    ESF_QUEUE_PUSH_ERROR,
    ESF_QUEUE_POP_ERROR,
    ESF_CONNECTIVITY_ERROR,
    ESF_CONNECTIVITY_SEND_ERROR,
    ESF_CONNECTIVITY_RECEIVE_ERROR,
    ESF_MOTOR_HELPER_REGISTER_ERROR,
    ESF_MOTOR_NOT_REGISTERD_TO_HELPER,
    ESF_MOTOR_HELPER_DATA_INVALIED,
};